name:                website
version:             0.1.0.0
github:              "githubuser/website"
license:             BSD3
author:              "Stefan Church"
maintainer:          "stefan.church@gmail.com"
copyright:           "2018 Stefan Church"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/schurch/website-template#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - scotty
    - wai-extra
    - text
    - mtl
    - data-default-class
    - wai-session
    - postgresql-transactional
    - transformers
    - postgresql-simple
    - wai-middleware-static
    - wai-session
    - vault
    - wai
    - warp
    - wai-session-postgresql
    - lucid

executables:
  website-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - website
    - scotty
    - wai-extra
    - text
    - postgresql-transactional
    - postgresql-simple
    - wai-middleware-static
    - wai
    - transformers
    - mtl
    - lucid

tests:
  website-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - website
